"""Universal Brain - Persistence & Durability Subsystem."""

from .engine import DatabaseManager
from .errors import (
    ConstraintViolationError,
    DatabaseUnavailableError,
    FencedEpochError,
    IntegrityFailureError,
    KernelSplitBrainError,
    OptimisticConcurrencyError,
    PersistenceError,
    PersistenceTimeoutError,
    RecoveryRequiredError,
    StaleVersionError,
)
from .models import (
    ActiveContractPointerORM,
    AlignmentContractORM,
    Base,
    CapabilityGrantORM,
    EventEdgeORM,
    EventORM,
    EvidenceORM,
    HandoffSnapshotORM,
    KernelLifecycleORM,
    ModelLeaseORM,
    OutboxRecordORM,
    ProjectORM,
    TaskDependencyORM,
    TaskORM,
    WorkerCheckpointORM,
    WorkerJobORM,
    WorkspaceCheckpointORM,
)
from .unit_of_work import TransactionCommitReceipt, TransactionState, UnitOfWork

__all__ = [
    "DatabaseManager",
    "Base",
    "UnitOfWork",
    "TransactionState",
    "TransactionCommitReceipt",
    "PersistenceError",
    "DatabaseUnavailableError",
    "PersistenceTimeoutError",
    "ConstraintViolationError",
    "OptimisticConcurrencyError",
    "StaleVersionError",
    "IntegrityFailureError",
    "FencedEpochError",
    "KernelSplitBrainError",
    "RecoveryRequiredError",
    "ProjectORM",
    "EventORM",
    "EventEdgeORM",
    "AlignmentContractORM",
    "ActiveContractPointerORM",
    "TaskORM",
    "TaskDependencyORM",
    "EvidenceORM",
    "CapabilityGrantORM",
    "ModelLeaseORM",
    "HandoffSnapshotORM",
    "WorkerJobORM",
    "WorkerCheckpointORM",
    "WorkspaceCheckpointORM",
    "OutboxRecordORM",
    "KernelLifecycleORM",
]
